### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by mpadmaraj** [serverless/event-gateway-sdk#53]
I'm having hard time enabling CORS for my POST http endpoint. Here is my function snippet from yml

```yml
functions:
  sendMessage:
    handler: handler.send
    events:
      - eventgateway:
          type: sync
          eventType: http.request
          path: /send/message
          method: POST
          cors: true
```

I'm using `0.6.1` version of `event-gateway-sdk`. I also tried to pass back the `Access-Control-Allow-Origin` from my function but for OPTIONS my function wasn't getting called. I think the gateway is handling it but not sure how to set the right header via the yml file

**Comment by alexdebrie** [comment]
Hey @mpadmaraj, thanks for reporting this. Let's see if we can get it figured out.

Are you using our hosted Event Gateway, or are you running your own Event Gateway? If you're running the hosted Event Gateway, can you paste the output of this command:

```bash
curl -X GET \
  https://config.slsgateway.com/v1/spaces/${APP_NAME}/cors \
  -H 'Authorization: Bearer ${EVENT_GATEWAY_ACCESS_KEY}'
```

Please replace `${APP_NAME}` with the name of your app and `${EVENT_GATEWAY_ACCESS_KEY}` with your access key.

**Comment by mpadmaraj** [comment]
I tried with my APP_NAME and EVENT_GATEWAY_ACCESS_KEY but get this error:
`{"errors":[{"message":"You're not authorized to access this resource."}]}`

**Comment by alexdebrie** [comment]
Thanks for the additional info, @mpadmaraj.

What version of the `serverless-event-gateway-plugin` are you using?

**Comment by mpadmaraj** [comment]
it is `0.7.4`

**Comment by alexdebrie** [comment]
Thanks @mpadmaraj. There's nothing I can see that's clearly wrong.

Could you try running an `sls deploy` again, then checking the CORS API endpoint?

**Comment by mpadmaraj** [comment]
I got the same response: `{"cors":[]}`. My `sls` version is `1.28.0` which is the latest. could that be a problem?

**Comment by alexdebrie** [comment]
Thanks @mpadmaraj. I'm still not quite sure why this isn't working.

Are you able to remove and redeploy your entire service? `sls remove`, then `sls deploy` ?

**Comment by mpadmaraj** [comment]
that worked!!!! Thanks @alexdebrie :+1:

**Comment by alexdebrie** [comment]
Great! Thanks, @mpadmaraj. I'll close this one, and the similar one in the plugin repo.

Feel free to reach out if you have additional questions.

**Comment by mpadmaraj** [comment]
Thanks @alexdebrie ! Can we by default add `OPTIONS`  in `allowedMethods`?

**Comment by alexdebrie** [comment]
@mpadmaraj I'm going to let @mthenw chime on in whether we can add `OPTIONS` as a default.

In the meantime, you can specify all CORS options yourself if you'd like:

```yml
functions:
  sendMessage:
    handler: handler.send
    events:
      - eventgateway:
          type: sync
          eventType: http.request
          path: /send/message
          method: POST
          cors: 
            origins: "*"
            methods:
              - GET
              - POST
              - OPTIONS
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
```

**Comment by mpadmaraj** [comment]
Sure @alexdebrie . I had to make a minor change in `origins` to deploy:
```yml
functions:
  sendMessage:
    handler: handler.send
    events:
      - eventgateway:
          type: sync
          eventType: http.request
          path: /send/message
          method: POST
          cors:
            origins: 
              - "*"
            methods:
              - GET
              - POST
              - OPTIONS
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
```

But with this the config endpoint gives empty `cors`:
`{"cors":[]}`
