### ISSUE TITLE
CORS is getting set for wrong path

### ISSUE THREAD

**Issue by mpadmaraj** [serverless/event-gateway-sdk#56]
I was setting up CORS for my POST endpoint `/send/message`. Initially I tried with `cors:true` but what I found was that it was not setting `OPTIONS` in `allowedMethods`. So on suggestion by @alexdebrie I used the below configuration:
```yml
sendMessage:
    handler: handler.send
    events:
      - eventgateway:
          type: sync
          eventType: http.request
          path: /send/message
          method: POST
          cors:
            origins: 
              - "*"
            methods:
              - GET
              - POST
              - OPTIONS
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
```
Now when I hit the `config` endpoint:
`curl -X GET   https://config.slsgateway.com/v1/spaces/padmaraj-appmail/cors   -H 'Authorization: Bearer AKQKffsdwIckaffNEM5292j15bbaetI5zVFvWhdEkmEcn'`
```JSON
{
  "cors": [
    {
      "space": "padmaraj-appmail",
      "corsId": "POST%2Fpadmaraj-appmail%2Fsend%2Fmessage",
      "method": "POST",
      "path": "/tenant-app/send/message",
      "allowedOrigins": [
        "*"
      ],
      "allowedMethods": [
        "GET",
        "POST",
        "OPTIONS"
      ],
      "allowedHeaders": [
        "Content-Type",
        "Authorization"
      ],
      "allowCredentials": true,
      "metadata": {
        "service": "send-notification",
        "stage": "dev"
      }
    }
  ]
}
```
the path for which CORS is set is for `/tenant-app/send/message` while the URL that is configured on the gateway(which I was able to hit to get results) is `/send/message`.
I have 2 questions:
1. Is there a way to make `CORS: true` to include `OPTIONS` method also?
2. How can tweak the above configuration so that it sets the path without the tenant and the app name?
Any help is highly appreciated!
