### ISSUE TITLE
Wrong url set with multiple applications

### ISSUE THREAD

**Issue by mpadmaraj** [serverless/event-gateway-sdk#57]
I initially had Application `appmail`. I deployed to AWS with this `app`. Later I decided to create a new application `sendmail`. Now when I created and deployed the app for some reason the url that was set up was against the first app `appmail`.

**Comment by ganeshvlrk** [comment]
@mpadmaraj Did you update the app related values in serverless.yml before redeploying? Can you please share the same

**Comment by mpadmaraj** [comment]
```yml

service: sls-mailer
app: sendmail
tenant: padmaraj

custom:
  eventgateway:
    url: ${env:EVENT_GATEWAY_APPLICATION}
    accessKey: ${env:EVENT_GATEWAY_ACCESS_KEY}
  eventTypes:
    http.request
    appment.sendMail
  bucket: serverless-email-attachment

plugins:
  - "@serverless/serverless-event-gateway-plugin"
  - serverless-plugin-browserifier
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  
  stage: dev
  region: ap-south-1
  environment:
     URL: ${self:custom.eventgateway.url}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  httpHandler:
    handler: functions/httpHandler.main
    environment: 
      S3_BUCKET_NAME: ${self:custom.bucket}
    package:
      include:
        - functions/parser.js
    events:
      - eventgateway:
          type: sync
          eventType: http.request
          path: /message
          method: POST
          cors:
            origins: 
              - "*"
            methods:
              - GET
              - POST
              - OPTIONS
            headers:
              - Content-Type
              - Authorization
              - Mail-Token
            allowCredentials: true
  sendMail:
    handler: functions/sendMail.main
    environment:
      senderEmail: ${env:MAIL_SMTP_FROM}
      receiverEmail: abc@gmail.com
      host: ${env:MAIL_SMTP}
      user: ${env:MAIL_SMTP_USER}
      password: ${env:MAIL_SMTP_PASSWORD}
    events:
      - eventgateway:
          type: async
          eventType: appment.sendMail
```

I also did `sls remove` and `sls deploy`.
I could see that even after `sls remove` I have the `.serverless` folder and this has `url` in `serverless-state.json` pointing to old app. Could that be an issue?
